fault -inject -time 0 -type SA0 {testbench_bist.top_level.clock}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.circuito06_n_118}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_228}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.scan_in}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_250}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.circuito06_coda0[0]}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.circuito06_n_21}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.circuito06_n_107}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_238}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.circuito06_coda0[1]}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.circuito06_n_15}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.circuito06_n_101}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_241}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.circuito06_coda0[2]}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.circuito06_n_14}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.circuito06_n_113}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_237}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.circuito06_coda1[0]}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.circuito06_n_25}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.circuito06_n_108}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_242}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.circuito06_coda1[1]}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.circuito06_n_24}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.circuito06_n_115}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_239}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.circuito06_coda1[2]}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.circuito06_n_22}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.circuito06_n_117}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_235}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.circuito06_coda2[0]}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.circuito06_n_23}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.circuito06_n_110}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_240}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.circuito06_coda2[1]}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.circuito06_n_16}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.circuito06_n_111}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_243}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.circuito06_coda2[2]}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.circuito06_n_17}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_234}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.circuito06_coda3[0]}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.circuito06_n_18}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_236}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.circuito06_coda3[1]}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.circuito06_n_20}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_233}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.circuito06_coda3[2]}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.circuito06_n_19}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.circuito06_n_70}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.circuito06_fu1}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.circuito06_n_8}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_204}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.circuito06_fu2}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.circuito06_n_7}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_201}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.circuito06_fu3}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.circuito06_n_6}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_202}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.circuito06_fu4}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.circuito06_n_9}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.circuito06_n_77}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_214}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.po[0]}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.circuito06_n_11}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_211}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.po[1]}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.circuito06_n_10}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_212}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.po[2]}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.circuito06_n_13}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_213}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.po[3]}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.circuito06_n_12}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.circuito06_n_49}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_199}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.circuito06_ru1}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.circuito06_n_4}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.circuito06_n_48}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_197}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.circuito06_ru2}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.circuito06_n_1}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.circuito06_n_45}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_200}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.circuito06_ru3}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.circuito06_n_2}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.circuito06_n_44}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_198}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.circuito06_ru4}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.circuito06_n_3}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.circuito06_n_35}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.circuito06_stato[0]}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.circuito06_n_0}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.circuito06_n_50}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.circuito06_stato[1]}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.scan_out}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.controller_Q1}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_249}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_54}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_252}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.bist_end}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.controller_n_203}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_174}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.vector[3]}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_247}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.vector[2]}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_246}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.vector[1]}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_245}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.vector[0]}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_244}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.bist_start}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.controller_Q2}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_209}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_222}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_181}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_165}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_229}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_168}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_231}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_225}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_167}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_172}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_169}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_175}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_232}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_203}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_178}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_205}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_230}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_224}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_223}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_217}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_208}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_196}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_215}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_180}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_176}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_216}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_207}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_177}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_206}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_191}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_190}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_170}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_193}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_187}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_179}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_173}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_195}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_171}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_186}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_182}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_189}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_194}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.reset_internal}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_183}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.pi[2]}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_185}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.pi[0]}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.pi[3]}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.pi[1]}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.bist_running}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_184}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_251}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_166}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.controller_state[0]}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.controller_state[1]}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.reset}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.new_seq}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_19}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.controller_per_count[0]}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_109}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.controller_per_count[1]}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_132}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.controller_per_count[2]}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_144}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.controller_per_count[3]}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_147}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.controller_per_count[4]}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_1}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_55}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_0}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.controller_seq_count[0]}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_99}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.controller_seq_count[1]}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_118}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.controller_seq_count[2]}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_134}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.controller_seq_count[3]}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_145}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.controller_seq_count[4]}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_152}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.controller_seq_count[5]}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_156}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.controller_seq_count[6]}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_161}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.controller_seq_count[7]}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_3}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_9}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_163}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.controller_seq_count[8]}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_2}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_139}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_4}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_117}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_42}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_63}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_14}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_33}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_52}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_112}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_8}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.inputLFSR_x[4]}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_60}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_50}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.output_misr[0]}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_29}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.output_misr[1]}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_27}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.output_misr[2]}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_20}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.output_misr[3]}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_48}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.output_misr[4]}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_103}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.output_misr[5]}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_101}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.output_misr[6]}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_102}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.output_misr[7]}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_100}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.output_misr[8]}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_119}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.misr_z[9]}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_6}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_138}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.pass_nfail}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_67}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_49}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.stateLFSR_y[0]}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_47}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_66}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_45}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.stateLFSR_y[2]}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_44}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.stateLFSR_y[3]}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_26}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.stateLFSR_y[4]}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_39}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.stateLFSR_y[5]}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_65}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_41}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.stateLFSR_y[6]}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_38}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.stateLFSR_y[7]}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_37}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.stateLFSR_y[8]}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_46}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.stateLFSR_y[9]}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_64}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_58}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.stateLFSR_y[10]}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_34}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.stateLFSR_y[11]}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_40}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.stateLFSR_y[12]}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_62}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_53}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.stateLFSR_y[13]}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_23}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.stateLFSR_y[14]}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_61}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_31}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.stateLFSR_y[15]}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_28}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.stateLFSR_y[16]}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_30}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.stateLFSR_y[17]}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_32}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.stateLFSR_y[18]}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_43}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.stateLFSR_y[19]}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_22}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.stateLFSR_y[20]}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_51}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.stateLFSR_y[21]}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_25}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.stateLFSR_y[22]}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_24}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.stateLFSR_y[23]}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_21}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.stateLFSR_y[24]}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_126}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_120}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.stateLFSR_y[25]}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_5}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_160}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_159}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_158}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_154}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_155}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_149}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_150}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_141}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_142}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_136}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_143}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_130}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_133}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_10}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_7}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_56}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_125}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_57}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_123}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_137}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_131}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_13}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_106}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_107}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_95}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_124}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_98}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_105}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_104}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_108}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_97}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_18}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_11}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_16}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_35}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_15}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_17}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_36}
fault -inject -time 0 -type SA0 {testbench_bist.top_level.n_96}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.clock}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_228}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.scan_in}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_250}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.circuito06_coda0[0]}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.circuito06_n_21}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_238}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.circuito06_coda0[1]}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.circuito06_n_15}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_241}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.circuito06_coda0[2]}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.circuito06_n_14}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_237}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.circuito06_coda1[0]}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.circuito06_n_25}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_242}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.circuito06_coda1[1]}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.circuito06_n_24}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_239}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.circuito06_coda1[2]}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.circuito06_n_22}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_235}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.circuito06_coda2[0]}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.circuito06_n_23}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_240}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.circuito06_coda2[1]}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.circuito06_n_16}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_243}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.circuito06_coda2[2]}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.circuito06_n_17}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.circuito06_n_116}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_234}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.circuito06_coda3[0]}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.circuito06_n_18}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.circuito06_n_112}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_236}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.circuito06_coda3[1]}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.circuito06_n_20}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.circuito06_n_109}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_233}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.circuito06_coda3[2]}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.circuito06_n_19}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.circuito06_n_70}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.circuito06_fu1}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.circuito06_n_8}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.circuito06_n_68}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_204}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.circuito06_fu2}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.circuito06_n_7}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.circuito06_n_69}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_201}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.circuito06_fu3}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.circuito06_n_6}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.circuito06_n_71}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_202}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.circuito06_fu4}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.circuito06_n_9}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_214}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.po[0]}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.circuito06_n_11}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.circuito06_n_78}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_219}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_211}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.po[1]}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.circuito06_n_10}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.circuito06_n_85}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_218}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_212}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.po[2]}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.circuito06_n_13}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.circuito06_n_84}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_220}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_213}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.po[3]}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.circuito06_n_12}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_199}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.circuito06_ru1}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.circuito06_n_4}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_197}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.circuito06_ru2}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.circuito06_n_1}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_200}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.circuito06_ru3}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.circuito06_n_2}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_198}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.circuito06_ru4}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.circuito06_n_3}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.circuito06_n_35}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.circuito06_stato[0]}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.circuito06_n_0}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.circuito06_n_50}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.circuito06_stato[1]}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.scan_out}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.controller_Q1}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_54}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_252}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.bist_end}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_174}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.vector[3]}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_247}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.vector[2]}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_246}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.vector[1]}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_245}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.vector[0]}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_244}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.bist_start}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_209}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_181}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_165}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_229}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_168}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_231}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_227}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_225}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_167}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_172}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_169}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_175}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_178}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_205}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_224}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_226}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_221}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_210}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_223}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_217}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_208}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_196}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_215}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_176}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_216}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_207}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_177}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_206}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_191}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_192}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_190}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_170}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_193}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_187}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_173}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_195}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_171}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_186}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_182}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_189}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_194}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.reset_internal}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_188}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_183}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.pi[2]}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_185}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.pi[0]}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.pi[3]}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.pi[1]}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.bist_running}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_184}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_166}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.controller_state[0]}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.controller_state[1]}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.reset}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.new_seq}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_93}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_19}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.controller_per_count[0]}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_122}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_109}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.controller_per_count[1]}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_135}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_132}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.controller_per_count[2]}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_146}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_144}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.controller_per_count[3]}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_151}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_147}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.controller_per_count[4]}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_55}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_59}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_0}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.controller_seq_count[0]}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_110}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_99}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.controller_seq_count[1]}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_128}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_118}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.controller_seq_count[2]}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_140}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_134}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.controller_seq_count[3]}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_148}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_145}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.controller_seq_count[4]}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_153}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_152}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.controller_seq_count[5]}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_157}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_156}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.controller_seq_count[6]}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_162}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_161}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.controller_seq_count[7]}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_9}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_164}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_163}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.controller_seq_count[8]}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_139}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_4}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_127}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_117}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_84}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_42}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_14}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_81}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_33}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_80}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_52}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_8}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.inputLFSR_x[4]}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_50}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.output_misr[0]}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_75}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_29}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.output_misr[1]}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_72}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_27}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.output_misr[2]}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_77}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_20}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.output_misr[3]}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_69}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_48}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.output_misr[4]}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_111}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_103}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.output_misr[5]}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_116}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_101}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.output_misr[6]}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_113}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_102}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.output_misr[7]}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_115}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_100}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.output_misr[8]}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_129}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_119}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.misr_z[9]}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_6}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_138}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.pass_nfail}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_49}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.stateLFSR_y[0]}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_92}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_47}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_45}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.stateLFSR_y[2]}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_91}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_44}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.stateLFSR_y[3]}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_90}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_26}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.stateLFSR_y[4]}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_89}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_39}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.stateLFSR_y[5]}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_41}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.stateLFSR_y[6]}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_86}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_38}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.stateLFSR_y[7]}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_94}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_37}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.stateLFSR_y[8]}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_83}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_46}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.stateLFSR_y[9]}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_58}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.stateLFSR_y[10]}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_82}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_34}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.stateLFSR_y[11]}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_87}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_40}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.stateLFSR_y[12]}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_53}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.stateLFSR_y[13]}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_79}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_23}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.stateLFSR_y[14]}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_31}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.stateLFSR_y[15]}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_88}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_28}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.stateLFSR_y[16]}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_78}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_30}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.stateLFSR_y[17]}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_85}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_32}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.stateLFSR_y[18]}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_68}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_43}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.stateLFSR_y[19]}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_76}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_22}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.stateLFSR_y[20]}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_74}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_51}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.stateLFSR_y[21]}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_73}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_25}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.stateLFSR_y[22]}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_71}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_24}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.stateLFSR_y[23]}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_70}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_21}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.stateLFSR_y[24]}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_120}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.stateLFSR_y[25]}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_5}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_160}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_159}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_158}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_154}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_155}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_149}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_150}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_141}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_142}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_136}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_143}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_130}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_133}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_7}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_56}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_57}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_123}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_137}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_131}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_13}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_114}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_107}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_121}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_95}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_124}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_105}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_104}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_108}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_18}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_12}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_11}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_16}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_35}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_15}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_17}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_36}
fault -inject -time 0 -type SA1 {testbench_bist.top_level.n_96}
