`timescale 1us/1ps 
// Generated by Cadence Genus(TM) Synthesis Solution 19.14-s108_1
// Generated on: Jan  8 2024 00:33:23 WET (Jan  8 2024 00:33:23 UTC)

// Verification Directory fv/circuito06 

module circuito06(clock, reset, request1, request2, request3, request4,
     grant_o, scan_en, scan_in, scan_out);
  input clock, reset, request1, request2, request3, request4, scan_en,
       scan_in;
  output [3:0] grant_o;
  output scan_out;
  wire clock, reset, request1, request2, request3, request4, scan_en,
       scan_in;
  wire [3:0] grant_o;
  wire scan_out;
  wire [2:0] coda1;
  wire [2:0] coda2;
  wire [2:0] coda0;
  wire [2:0] coda3;
  wire [1:0] stato;
  wire fu1, fu2, fu3, fu4, n_0, n_1, n_2, n_3;
  wire n_4, n_6, n_7, n_8, n_9, n_10, n_11, n_12;
  wire n_13, n_14, n_15, n_16, n_17, n_18, n_19, n_20;
  wire n_21, n_22, n_23, n_24, n_25, n_26, n_27, n_28;
  wire n_29, n_30, n_31, n_32, n_33, n_34, n_35, n_36;
  wire n_37, n_38, n_39, n_40, n_41, n_42, n_43, n_44;
  wire n_45, n_46, n_47, n_48, n_49, n_50, n_51, n_52;
  wire n_53, n_54, n_55, n_56, n_57, n_58, n_59, n_60;
  wire n_61, n_62, n_63, n_64, n_65, n_66, n_67, n_68;
  wire n_69, n_70, n_71, n_72, n_73, n_74, n_75, n_76;
  wire n_77, n_78, n_79, n_80, n_81, n_82, n_83, n_84;
  wire n_85, n_86, n_87, n_88, n_89, n_90, n_91, n_92;
  wire n_93, n_94, n_95, n_96, n_97, n_98, n_99, n_100;
  wire n_101, n_102, n_103, n_104, n_105, n_106, n_107, n_108;
  wire n_109, n_110, n_111, n_112, n_113, n_114, n_115, n_116;
  wire n_117, n_118, ru1, ru2, ru3, ru4;
  DFS1 \coda1_reg[0] (.C (clock), .D (n_113), .SD (n_14), .SE
       (scan_en), .Q (coda1[0]), .QN (n_25));
  DFS1 \coda1_reg[1] (.C (clock), .D (n_108), .SD (n_25), .SE
       (scan_en), .Q (coda1[1]), .QN (n_24));
  DFS1 \coda2_reg[0] (.C (clock), .D (n_117), .SD (n_22), .SE
       (scan_en), .Q (coda2[0]), .QN (n_23));
  DFS1 \coda1_reg[2] (.C (clock), .D (n_115), .SD (n_24), .SE
       (scan_en), .Q (coda1[2]), .QN (n_22));
  DFS1 \coda0_reg[0] (.C (clock), .D (n_118), .SD (scan_in), .SE
       (scan_en), .Q (coda0[0]), .QN (n_21));
  DFS1 \coda3_reg[1] (.C (clock), .D (n_112), .SD (n_18), .SE
       (scan_en), .Q (coda3[1]), .QN (n_20));
  DFS1 \coda3_reg[2] (.C (clock), .D (n_109), .SD (n_20), .SE
       (scan_en), .Q (coda3[2]), .QN (n_19));
  DFS1 \coda3_reg[0] (.C (clock), .D (n_116), .SD (n_17), .SE
       (scan_en), .Q (coda3[0]), .QN (n_18));
  DFS1 \coda2_reg[2] (.C (clock), .D (n_111), .SD (n_16), .SE
       (scan_en), .Q (coda2[2]), .QN (n_17));
  DFS1 \coda2_reg[1] (.C (clock), .D (n_110), .SD (n_23), .SE
       (scan_en), .Q (coda2[1]), .QN (n_16));
  DFS1 \coda0_reg[1] (.C (clock), .D (n_107), .SD (n_21), .SE
       (scan_en), .Q (coda0[1]), .QN (n_15));
  DFS1 \coda0_reg[2] (.C (clock), .D (n_101), .SD (n_15), .SE
       (scan_en), .Q (coda0[2]), .QN (n_14));
  OAI2111 g2533__2398(.A (fu3), .B (n_89), .C (n_91), .D (n_106), .Q
       (n_118));
  OAI212 g2542__5107(.A (n_32), .B (n_114), .C (n_95), .Q (n_117));
  CLKIN3 g2555(.A (n_105), .Q (n_116));
  OAI212 g2543__6260(.A (n_72), .B (n_114), .C (n_99), .Q (n_115));
  OAI212 g2544__4319(.A (n_39), .B (n_114), .C (n_96), .Q (n_113));
  CLKIN3 g2547(.A (n_104), .Q (n_112));
  OAI212 g2546__8428(.A (n_31), .B (n_114), .C (n_92), .Q (n_111));
  OAI212 g2545__5526(.A (n_30), .B (n_114), .C (n_94), .Q (n_110));
  CLKIN3 g2548(.A (n_100), .Q (n_109));
  OAI212 g2538__6783(.A (n_26), .B (n_114), .C (n_98), .Q (n_108));
  NAND31 g2532__3680(.A (n_93), .B (n_106), .C (n_87), .Q (n_107));
  AOI221 g2561__1617(.A (n_103), .B (coda3[0]), .C (n_102), .D
       (coda2[0]), .Q (n_105));
  AOI221 g2549__2802(.A (n_103), .B (coda3[1]), .C (n_102), .D
       (coda2[1]), .Q (n_104));
  NAND22 g2537__1705(.A (n_90), .B (n_88), .Q (n_101));
  AOI221 g2551__5122(.A (n_103), .B (coda3[2]), .C (n_102), .D
       (coda2[2]), .Q (n_100));
  AOI221 g2556__8246(.A (n_103), .B (coda1[2]), .C (n_97), .D
       (coda2[2]), .Q (n_99));
  AOI221 g2554__7098(.A (n_103), .B (coda1[1]), .C (n_97), .D
       (coda2[1]), .Q (n_98));
  AOI221 g2553__6131(.A (n_103), .B (coda1[0]), .C (n_97), .D
       (coda2[0]), .Q (n_96));
  AOI221 g2557__1881(.A (n_103), .B (coda2[0]), .C (n_97), .D
       (coda3[0]), .Q (n_95));
  AOI221 g2558__5115(.A (n_103), .B (coda2[1]), .C (n_97), .D
       (coda3[1]), .Q (n_94));
  AOI221 g2550__7482(.A (n_103), .B (coda0[1]), .C (n_97), .D
       (coda1[1]), .Q (n_93));
  AOI221 g2559__4733(.A (n_103), .B (coda2[2]), .C (n_97), .D
       (coda3[2]), .Q (n_92));
  AOI221 g2560__6161(.A (n_103), .B (coda0[0]), .C (n_97), .D
       (coda1[0]), .Q (n_91));
  AOI221 g2552__9315(.A (n_103), .B (coda0[2]), .C (n_97), .D
       (coda1[2]), .Q (n_90));
  INV3 g2569(.A (n_102), .Q (n_114));
  DFS1 \grant_reg[2] (.C (clock), .D (n_85), .SD (n_10), .SE (scan_en),
       .Q (grant_o[2]), .QN (n_13));
  DFS1 \grant_reg[3] (.C (clock), .D (n_84), .SD (n_13), .SE (scan_en),
       .Q (grant_o[3]), .QN (n_12));
  OAI2111 g2572__9945(.A (fu3), .B (n_89), .C (n_88), .D (n_87), .Q
       (n_102));
  DFS1 \grant_reg[0] (.C (clock), .D (n_77), .SD (n_9), .SE (scan_en),
       .Q (grant_o[0]), .QN (n_11));
  DFS1 \grant_reg[1] (.C (clock), .D (n_78), .SD (n_11), .SE (scan_en),
       .Q (grant_o[1]), .QN (n_10));
  NAND22 g2564__2883(.A (n_86), .B (n_82), .Q (n_103));
  AOI211 g2575__2346(.A (n_81), .B (n_29), .C (n_83), .Q (n_88));
  DFS1 fu4_reg(.C (clock), .D (n_71), .SD (n_6), .SE (scan_en), .Q
       (fu4), .QN (n_9));
  DFS1 fu1_reg(.C (clock), .D (n_70), .SD (n_19), .SE (scan_en), .Q
       (fu1), .QN (n_8));
  DFS1 fu2_reg(.C (clock), .D (n_68), .SD (n_8), .SE (scan_en), .Q
       (fu2), .QN (n_7));
  DFS1 fu3_reg(.C (clock), .D (n_69), .SD (n_7), .SE (scan_en), .Q
       (fu3), .QN (n_6));
  AOI311 g2570__1666(.A (fu2), .B (ru2), .C (n_62), .D (n_76), .Q
       (n_86));
  AOI211 g2566__7410(.A (n_73), .B (n_63), .C (reset), .Q (n_85));
  NOR21 g2565__6417(.A (reset), .B (n_79), .Q (n_84));
  INV2 g2579(.A (n_83), .Q (n_106));
  AOI221 g2577__5477(.A (n_74), .B (n_80), .C (n_81), .D (fu1), .Q
       (n_82));
  NOR21 g2580__2398(.A (n_80), .B (n_75), .Q (n_83));
  AOI221 g2571__5107(.A (n_60), .B (coda0[2]), .C (n_66), .D
       (grant_o[3]), .Q (n_79));
  NOR21 g2573__6260(.A (reset), .B (n_67), .Q (n_78));
  AOI211 g2574__4319(.A (n_65), .B (n_64), .C (reset), .Q (n_77));
  OAI222 g2578__8428(.A (n_59), .B (reset), .C (n_89), .D (n_27), .Q
       (n_76));
  DFS1 \stato_reg[1] (.C (clock), .D (n_50), .SD (n_0), .SE (scan_en),
       .Q (stato[1]), .QN (scan_out));
  INV2 g2589(.A (n_74), .Q (n_75));
  NAND31 g2576__5526(.A (n_61), .B (n_72), .C (coda0[1]), .Q (n_73));
  NOR31 g2593__6783(.A (n_58), .B (ru2), .C (ru3), .Q (n_74));
  DFS1 ru1_reg(.C (clock), .D (n_49), .SD (n_12), .SE (scan_en), .Q
       (ru1), .QN (n_4));
  DFS1 ru4_reg(.C (clock), .D (n_44), .SD (n_2), .SE (scan_en), .Q
       (ru4), .QN (n_3));
  DFS1 ru3_reg(.C (clock), .D (n_45), .SD (n_1), .SE (scan_en), .Q
       (ru3), .QN (n_2));
  DFS1 ru2_reg(.C (clock), .D (n_48), .SD (n_4), .SE (scan_en), .Q
       (ru2), .QN (n_1));
  NOR21 g2604__3680(.A (reset), .B (n_56), .Q (n_71));
  AOI211 g2603__1617(.A (n_57), .B (n_51), .C (reset), .Q (n_70));
  NOR21 g2602__2802(.A (reset), .B (n_53), .Q (n_69));
  NOR21 g2605__1705(.A (reset), .B (n_54), .Q (n_68));
  IMUX21 g2582__5122(.A (n_40), .B (grant_o[1]), .S (n_66), .Q (n_67));
  NAND41 g2591__8246(.A (n_52), .B (coda0[1]), .C (coda0[0]), .D
       (coda0[2]), .Q (n_65));
  NAND22 g2584__7098(.A (n_66), .B (grant_o[0]), .Q (n_64));
  NAND22 g2583__6131(.A (n_66), .B (grant_o[2]), .Q (n_63));
  NAND31 g2592__1881(.A (n_62), .B (n_33), .C (ru2), .Q (n_87));
  NOR21 g2595__5115(.A (coda0[0]), .B (n_66), .Q (n_61));
  NOR31 g2581__7482(.A (n_66), .B (coda0[0]), .C (coda0[1]), .Q (n_60));
  NAND31 g2594__4733(.A (n_62), .B (n_28), .C (ru3), .Q (n_89));
  NOR21 g2596__6161(.A (reset), .B (n_66), .Q (n_97));
  IMUX21 g2590__9315(.A (n_46), .B (n_55), .S (n_47), .Q (n_59));
  INV2 g2612(.A (n_62), .Q (n_58));
  NOR21 g2611__9945(.A (reset), .B (n_57), .Q (n_81));
  IMUX21 g2614__2883(.A (ru4), .B (fu4), .S (n_55), .Q (n_56));
  IMUX21 g2615__2346(.A (ru2), .B (fu2), .S (n_55), .Q (n_54));
  IMUX21 g2616__1666(.A (ru3), .B (fu3), .S (n_55), .Q (n_53));
  DFS1 \stato_reg[0] (.C (clock), .D (n_35), .SD (n_3), .SE (scan_en),
       .Q (stato[0]), .QN (n_0));
  INV3 g2601(.A (n_52), .Q (n_66));
  NAND22 g2619__7410(.A (n_55), .B (fu1), .Q (n_51));
  NOR21 g2620__6417(.A (reset), .B (n_55), .Q (n_50));
  NOR31 g2618__5477(.A (n_55), .B (ru1), .C (reset), .Q (n_62));
  NOR21 g2607__2398(.A (reset), .B (n_42), .Q (n_49));
  NOR21 g2608__5107(.A (reset), .B (n_37), .Q (n_48));
  NOR21 g2606__6260(.A (n_47), .B (n_46), .Q (n_52));
  NOR21 g2609__4319(.A (reset), .B (n_38), .Q (n_45));
  NOR21 g2613__8428(.A (reset), .B (n_41), .Q (n_44));
  NAND22 g2621__5526(.A (n_43), .B (ru1), .Q (n_57));
  INV3 g2628(.A (n_43), .Q (n_55));
  IMUX21 g2624__6783(.A (request1), .B (ru1), .S (stato[0]), .Q (n_42));
  IMUX21 g2623__3680(.A (request4), .B (ru4), .S (stato[0]), .Q (n_41));
  NOR31 g2625__1617(.A (n_39), .B (coda0[1]), .C (coda0[2]), .Q (n_40));
  NOR40 g2617__2802(.A (fu3), .B (fu2), .C (fu1), .D (fu4), .Q (n_46));
  IMUX21 g2627__1705(.A (request3), .B (ru3), .S (stato[0]), .Q (n_38));
  IMUX21 g2626__5122(.A (request2), .B (ru2), .S (stato[0]), .Q (n_37));
  NAND22 g2629__8246(.A (n_36), .B (stato[1]), .Q (n_47));
  NOR21 g2630__7098(.A (stato[1]), .B (n_36), .Q (n_43));
  NAND22 g2632__6131(.A (n_34), .B (ru4), .Q (n_80));
  NOR21 g2631__1881(.A (reset), .B (stato[0]), .Q (n_35));
  CLKIN2 g2639(.A (fu4), .Q (n_34));
  CLKIN2 g2634(.A (fu2), .Q (n_33));
  INV2 g2633(.A (coda1[0]), .Q (n_32));
  INV2 g2640(.A (coda1[2]), .Q (n_31));
  INV3 g2638(.A (stato[0]), .Q (n_36));
  CLKIN2 g2635(.A (coda0[0]), .Q (n_39));
  INV2 g2641(.A (coda1[1]), .Q (n_30));
  CLKIN2 g2642(.A (fu1), .Q (n_29));
  CLKIN2 g2636(.A (ru2), .Q (n_28));
  INV2 g2643(.A (fu3), .Q (n_27));
  INV2 g2644(.A (coda0[1]), .Q (n_26));
  INV2 g2637(.A (coda0[2]), .Q (n_72));
endmodule

